--[[
	Example to add translate

	["<Language code>"] = "Translated string",

	["#C2S"] = {
		["en"] = "Click to start",
		["zh-TW"] = "點擊開始",
		["zh-CN"] = "",
		["ja"] = "",
		["ru"] = "Нажмите, чтобы начать",
	},
]]

OSU.Lang = {
		["#STCustomKeyboard"] = {
			["en"] = "Customize key",
			["tr"] = "Tuşu özelleştir",
			["zh-TW"] = "自定義按鍵",
			["zh-CN"] = "",
			["ru"] = "Настройка клавиши",
			["ja"] = "カスタマイズキー",
		},
		["#DLDownload"] = {
			["en"] = "Downloads",
			["tr"] = "İndirilenler",
			["zh-TW"] = "已下載",
			["zh-CN"] = "",
			["ru"] = "Загрузки",
			["ja"] = "ダウンロード",
		},
		["#STAudio"] = {
			["en"] = "Audio",
			["tr"] = "Ses",
			["zh-TW"] = "音效",
			["zh-CN"] = "",
			["ru"] = "Аудио",
			["ja"] = "オーディオ",
		},
		["#STMainMenu"] = {
			["en"] = "Main Menu",
			["tr"] = "Ana Menü",
			["zh-TW"] = "主介面",
			["zh-CN"] = "",
			["ru"] = "Главное меню",
			["ja"] = "メインメニュー",
		},
		["#STLoad@2x"] = {
			["en"] = "Load high resolution images",
			["tr"] = "Yüksek çözünürlüklü görselleri yükle",
			["zh-TW"] = "載入高畫質材質",
			["zh-CN"] = "",
			["ru"] = "Загрузить изображения высокого разрешения",
			["ja"] = "高解像度画像の読み込み",
		},
		["#DLReset"] = {
			["en"] = "Reset",
			["tr"] = "Sıfırla",
			["zh-TW"] = "重製",
			["zh-CN"] = "",
			["ru"] = "Сброс",
			["ja"] = "リセット",
		},
		["#STMetaString"] = {
			["en"] = "Prefer metadata in original language",
			["tr"] = "Üst veriyi orijinal dilde tercih et",
			["zh-TW"] = "顯示地圖原文",
			["zh-CN"] = "",
			["ru"] = "Показывать метаданные песен на языке оригинала",
			["ja"] = "ビートマップの原文を表示する",
		},
		["#STNotify"] = {
			["en"] = "Type osu in console or type /osu in chat to play!",
			["tr"] = "Oynamak için konsolda osu veya sohbette /osu yazın!",
			["zh-TW"] = "在控制台輸入osu 或者在聊天室輸入/osu 即可開始遊戲",
			["zh-CN"] = "",
			["ru"] = "Введите osu в консоли или /osu в чате, чтобы играть!",
			["ja"] = "コンソールで ''osu'' と入力するか、チャットで ''/osu'' と入力してプレーする！",
		},
		["#STRGBRate"] = {
			["en"] = "RGB speed",
			["tr"] = "RGB hızı",
			["zh-TW"] = "RGB 速度",
			["zh-CN"] = "",
			["ru"] = "Скорость RGB",
			["ja"] = "RGB スビート",
		},
		["#STFPS"] = {
			["en"] = "Show FPS counter",
			["tr"] = "FPS sayacını göster",
			["zh-TW"] = "顯示FPS",
			["zh-CN"] = "",
			["ru"] = "Показывать счётчик кадров",
			["ja"] = "FPSを表示する",
		},
		["#ServerOffline"] = {
			["en"] = "Server is offline...",
			["tr"] = "Sunucu çevrim dışı...",
			["zh-TW"] = "無法連接到伺服器",
			["zh-CN"] = "",
			["ru"] = "Сервер отключён...",
			["ja"] = "サーバーがオフラインです...",
		},
		["#STLName"] = {
			["en"] = "Name & Leaderboard",
			["tr"] = "Ad ve Skor Tablosu",
			["zh-TW"] = "名稱與排行榜",
			["zh-CN"] = "",
			["ru"] = "Имя и таблица рекордов",
			["ja"] = "名前とランキング",
		},
		["#STCursorTrailSize"] = {
			["en"] = "Cursor trail size",
			["tr"] = "İmleç izi boyutu",
			["zh-TW"] = "游標軌跡大小",
			["zh-CN"] = "",
			["ru"] = "Размер следа от курсора",
			["ja"] = "カーソルの軌跡の大きさ",
		},
		["#STCursorTrail"] = {
			["en"] = "Cursor trail",
			["tr"] = "İmleç izi",
			["zh-TW"] = "游標軌跡",
			["zh-CN"] = "",
			["ru"] = "След от курсора",
			["ja"] = "カーソルの軌跡",
		},
		["#RankingTotalPlay"] = {
			["en"] = "Total Plays",
			["tr"] = "Toplam Oynanma",
			["zh-TW"] = "總遊玩次數",
			["zh-CN"] = "",
			["ru"] = "Всего игр",
			["ja"] = "総プレー数",
		},
		["#STTheme"] = {
			["en"] = "osu! music theme",
			["tr"] = "osu! müziği",
			["zh-TW"] = "osu! 主題曲",
			["zh-CN"] = "",
			["ru"] = "Музыкальная тема osu!",
			["ja"] = "osu!オリジナルのテーマを使用する",
		},
		["#STSteamName"] = {
			["en"] = "Use steam name for leaderboard",
			["tr"] = "Skor tablosu için steam adı kullan",
			["zh-TW"] = "使用Steam名稱",
			["zh-CN"] = "",
			["ru"] = "Использовать имя из Steam в таблице рекордов",
			["ja"] = "Steam のユーザー名前を使います",
		},
		["#STCards"] = {
			["en"] = "Load beatmap cards",
			["tr"] = "Beatmapleri yükle",
			["zh-TW"] = "載入圖譜預覽背景",
			["zh-CN"] = "",
			["ru"] = "Загружать карточки карт",
		},
		["#STNoBGFlash"] = {
			["en"] = "Disable background flashing effect",
			["tr"] = "Arka plan yanıp sönme efektini devre dışı bırak",
			["zh-TW"] = "關閉背景閃爍效果",
			["zh-CN"] = "",
			["ru"] = "Отключить эффект мигания фона",
			["ja"] = "背景の点滅効果を無効にする",
		},
		["#RankingScore"] = {
			["en"] = "Ranking Score",
			["tr"] = "Sıralama Skoru",
			["zh-TW"] = "積分",
			["zh-CN"] = "",
			["ru"] = "Рейтинг по очкам",
			["ja"] = "ランキングスコア",
		},
		["#DLDownloadFinished"] = {
			["en"] = "Download finished!",
			["tr"] = "İndirme tamamlandı!",
			["zh-TW"] = "下載完成",
			["zh-CN"] = "",
			["ru"] = "Скачивание завершено!",
			["ja"] = "ダウンロードは終了した！",
		},
		["#STHObject"] = {
			["en"] = "Hit Objects",
			["tr"] = "Tıklama Objeleri",
			["zh-TW"] = "打擊物件",
			["zh-CN"] = "",
			["ru"] = "Игровые объекты",
			["ja"] = "ヒットオブジェクト",
		},
		["#STMenuDim"] = {
			["en"] = "Menu background dim",
			["tr"] = "Menü arka plan sönüklüğü",
			["zh-TW"] = "主畫面亮度",
			["zh-CN"] = "",
			["ru"] = "Затемнение фона меню",
			["ja"] = "メニューの明るさ",
		},
		["#RankingName"] = {
			["en"] = "Player name",
			["tr"] = "Oyuncu adı",
			["zh-TW"] = "玩家名稱",
			["zh-CN"] = "",
			["ru"] = "Имя игрока",
			["ja"] = "プレイヤー名",
		},
		["#STRenderer"] = {
			["en"] = "Renderer",
			["tr"] = "Görüntü İşleyici",
			["zh-TW"] = "渲染",
			["zh-CN"] = "",
			["ru"] = "Отрисовка",
			["ja"] = "レンダリングエンジン",
		},
		["#SPWarning3"] = {
			["en"] = "Warning: osu cannot work on singleplayer",
			["tr"] = "Uyarı: osu tek kişilikte oynanamaz",
			["zh-TW"] = "警告: osu無法在單人模式下運作",
			["zh-CN"] = "",
			["ru"] = "Внимание: osu не может работать в одиночной игре",
			["ja"] = "警告: osuはシングルプレーヤーでは動作しません",
		},
		["#RankingLeaderboard"] = {
			["en"] = "Ranking Leaderboard",
			["tr"] = "Skor Tablosu",
			["zh-TW"] = "全球排行榜",
			["zh-CN"] = "",
			["ru"] = "Таблица рекордов рейтинга",
			["ja"] = "ランキングリーダーボード",
		},
		["#ModDiffSpec"] = {
			["en"] = "Special",
			["tr"] = "Özel",
			["zh-TW"] = "特殊",
			["zh-CN"] = "",
			["ru"] = "Специальное",
			["ja"] = "スペシャル",
		},
		["#BMLength"] = {
			["en"] = "Length",
			["tr"] = "Uzunluk",
			["zh-TW"] = "圖譜長度",
			["zh-CN"] = "",
			["ru"] = "Длина",
			["ja"] = "長さ",
		},
		["#ModDiffInc"] = {
			["en"] = "Difficulty Increase",
			["tr"] = "Zorluk Artırma",
			["zh-TW"] = "增加難度",
			["zh-CN"] = "",
			["ru"] = "Повышение сложности",
			["ja"] = "難易度の上昇",
		},
		["#ModDiffReduc"] = {
			["en"] = "Difficulty Reduction",
			["tr"] = "Zorluk Azaltma",
			["zh-TW"] = "減少難度",
			["zh-CN"] = "",
			["ru"] = "Снижение сложности",
			["ja"] = "難易度の軽減",
		},
		["#STAllEdgeSound"] = {
			["en"] = "Allow all edge sounds",
			["tr"] = "Kenar seslerinin tümüne izin ver",
			["zh-TW"] = "啟用全部的滑條擊中音效",
			["zh-CN"] = "",
			["ru"] = "Разрешить все краевые звуки",
			["ja"] = "すべてのエッジ音有効化",
		},
		["#ModNote"] = {
			["en"] = "Mods provide different ways to enjoy gameplay. Some have an effect on the score you can\n achieve during ranked play. Others are just for fun",
			["tr"] = "Modlar oyunun keyfini çıkarmanın farklı yollarını sunar. Bazıları sıralı maçlarda alabileceğiniz\n skoru etkileyebilir. Diğerleri ise sadece eğlenceliktir",
			["zh-TW"] = "開啟Mod可以讓你以不同模式享受遊戲，有些會影響你的分數，其他的僅供娛樂",
			["zh-CN"] = "",
			["ru"] = "Моды предоставляют различные способы наслаждения игрой. Некоторые из них влияют на очки,\n получаемые при прохождении рейтинговых карт. Другие просто забавы ради",
			["ja"] = "Modを有効にすると、異なるモードでゲームを楽しむことができます。\n一部はスコアに影響を与えることがありますが、他は単に娯楽を提供するものです。",
		},
		["#STDConnect"] = {
			["en"] = "Display connectpoints and curve type",
			["tr"] = "Bağlanma noktalarını ve eğim tipini göster",
			["zh-TW"] = "顯示曲線控制點和渲染數量",
			["zh-CN"] = "",
			["ru"] = "Отображение точек соединения и типа кривых",
			["ja"] = "接続点とカーブタイプを表示",
		},
		["#STMVol"] = {
			["en"] = "Music",
			["tr"] = "Müzik",
			["zh-TW"] = "音樂",
			["zh-CN"] = "",
			["ru"] = "Музыка",
			["ja"] = "音楽",
		},
		["#SPWarning2"] = {
			["en"] = "Go to 'Start new game's top right corner -> change it to atleast 2 players",
			["tr"] = "'Yeni oyun başlat' a gidin -> en az 2 kişilik olacak şekilde ayarlayın",
			["zh-TW"] = "從 '開始新遊戲' 的右上角進行變更",
			["zh-CN"] = "",
			["ru"] = "Перейдите в «Начать новую игру» в правом верхнем углу -> измените значение на минимум 2 игрока",
		},
		["#STCached"] = {
			["en"] = "Cached Datas",
			["tr"] = "Önbelleğe Alınmış Veriler",
			["zh-TW"] = "已快取檔案",
			["zh-CN"] = "",
			["ru"] = "Данные в кэше",
			["ja"] = "キャッシュデータ",
		},
		["#SPWarning1"] = {
			["en"] = "Gmod osu need to be in multiplayer mode in order to work",
			["tr"] = "Gmod osu'nun çalışması için çoklu oyuncu modunda olunması gerekiyor",
			["zh-TW"] = "Gmod osu 需要在多人模式下才可正常運作",
			["zh-CN"] = "",
			["ru"] = "Gmod osu должен быть запущен в сетевом режиме, чтобы работать",
			["ja"] = "Gmod osuはマルチプレイモードである必要があります",
		},
		["#STNoComboBreak"] = {
			["en"] = "Disable combobreak sound",
			["tr"] = "Kombo bozulma sesini devre dışı bırak",
			["zh-TW"] = "關閉斷Combo音效",
			["zh-CN"] = "",
			["ru"] = "Отключить звук промаха",
			["ja"] = "コンボブレイク音を無効にする",
		},
		["#STDSlider"] = {
			["en"] = "Sliders",
			["tr"] = "Kaydıraçlar",
			["zh-TW"] = "滑條",
			["zh-CN"] = "",
			["ru"] = "Ползунки",
			["ja"] = "スライダー",
		},
		["#STEdgeFlash"] = {
			["en"] = "Edge flashing",
			["tr"] = "Kenar ışığı yanıp sönmesi",
			["zh-TW"] = "螢幕邊緣閃爍",
			["zh-CN"] = "",
			["ru"] = "Мигающие края",
			["ja"] = "エッジフラッシュ",
		},
		["#STDebug"] = {
			["en"] = "Debugging",
			["tr"] = "Hata ayıklama",
			["zh-TW"] = "",
			["zh-CN"] = "",
			["ru"] = "Отладка",
		},
		["#STCacheWarning"] = {
			["en"] = "Deleting cached data will cause longer load time!",
			["tr"] = "Önbelleğe alınmış veriyi silmek açılma süresinin uzamasına sebep olacaktır!",
			["zh-TW"] = "刪除快取檔案會延長載入時間!",
			["zh-CN"] = "",
			["ru"] = "Удаление данных в кэше приведёт к увеличению времени загрузки!",
			["ja"] = "キャッシュされたデータを削除すると、ロード時間が長くなります！",
		},
		["#STClearCache"] = {
			["en"] = "Clear all cached datas",
			["tr"] = "Önbelleğe alınmış tüm verileri temizle",
			["zh-TW"] = "清除已快取檔案",
			["zh-CN"] = "",
			["ru"] = "Очистить все данные в кэше",
			["ja"] = "キャッシュされたデータをすべてクリアする",
		},
		["#STCache"] = {
			["en"] = "Cache",
			["tr"] = "Veri",	
			["zh-TW"] = "快取",
			["zh-CN"] = "",
			["ru"] = "Кэш",
			["ja"] = "キャッシュ",
		},
		["#Acc"] = {
			["en"] = "Accuracy",
			["tr"] = "Tutarlılık",
			["zh-TW"] = "準確度",
			["zh-CN"] = "",
			["ru"] = "Точность",
		},
		["#STLoggedIn-Yes"] = {
			["en"] = "Logged in",
			["tr"] = "Giriş yapıldı",
			["zh-TW"] = "已登入",
			["zh-CN"] = "",
			["ru"] = "Вошли",
			["ja"] = "ログイン済み",
		},
		["#BMSliders"] = {
			["en"] = "Sliders",
			["tr"] = "Kaydıraçlar",
			["zh-TW"] = "滑條",
			["zh-CN"] = "",
			["ru"] = "Ползунки",
			["ja"] = "スライダー",
		},
		["#ServerOnline"] = {
			["en"] = "Server is online!",
			["tr"] = "Sunucu çevrim içi!",
			["zh-TW"] = "已連接到伺服器!",
			["zh-CN"] = "",
			["ru"] = "Сервер работает!",
			["ja"] = "サーバーはオンラインです！",
		},
		["#STSentScore"] = {
			["en"] = "Submit score to leaderboard",
			["tr"] = "Skoru skor tablosuna gönder",
			["zh-TW"] = "送出成績到排行榜",
			["zh-CN"] = "",
			["ru"] = "Отправить результаты в таблицу рекордов",
			["ja"] = "スコアをリーダーボードに投稿する",
		},
		["#STDetails"] = {
			["en"] = "Detail Settings",
			["tr"] = "Ayrıntı Ayarları",
			["zh-TW"] = "細節設定",
			["zh-CN"] = "",
			["ru"] = "Настройка деталей",
			["ja"] = "詳細設定",
		},
		["#STNoAvatar"] = {
			["en"] = "Disable avatars on leaderboard",
			["tr"] = "Skor tablosunda avatarları devre dışı bırak",
			["zh-TW"] = "不顯示排行榜頭像",
			["zh-CN"] = "",
			["ru"] = "Отключить аватары в таблице рекордов",
			["ja"] = "リーダーボードのアバターを無効にする",
		},
		["#DLLagNotify"] = {
			["en"] = "Importing maps will cause\ntemporary lag",
			["tr"] = "Harita yüklemek kısa takılmalara\n sebep olabilir",
			["zh-TW"] = "導入圖譜時會暫時卡頓",
			["zh-CN"] = "",
			["ru"] = "Импортирование карт вызовет\nвременную задержку",
		},
		["#STVolume"] = {
			["en"] = "Volume",
			["tr"] = "Ses Düzeyi",
			["zh-TW"] = "音量",
			["zh-CN"] = "",
			["ru"] = "Громкость",
			["ja"] = "ボリューム",
		},
		["#STInput"] = {
			["en"] = "Input",
			["tr"] = "Giriş",
			["zh-TW"] = "輸入",
			["zh-CN"] = "",
			["ru"] = "Устройства ввода",
			["ja"] = "入力",
		},
		["#STForceBG"] = {
			["en"] = "Force default background",
			["tr"] = "Varsayılan arka planı zorla",
			["zh-TW"] = "強制使用預設背景",
			["zh-CN"] = "",
			["ru"] = "Принудительный фон по умолчанию",
			["ja"] = "デフォルトの背景を使います",
		},
		["#STCursorTrailGap"] = {
			["en"] = "Fill gap between cursor position",
			["tr"] = "İmleç konumu arasındaki boşluğu doldur",
			["zh-TW"] = "填滿間隔",
			["zh-CN"] = "",
			["ru"] = "Заполнить промежуток между положением курсора",
			["ja"] = "カーソル位置の隙間を埋める",
		},
		["#STShowThumbnails"] = {
			["en"] = "Show thumbnails",
			["tr"] = "Küçük resimleri göster",
			["zh-TW"] = "縮圖",
			["zh-CN"] = "",
			["ru"] = "Показывать миниатюры",
			["ja"] = "サムネイル表示",
		},
		["#STCursorTrailRGB"] = {
			["en"] = "RGB",
			["tr"] = "RGB",
			["zh-TW"] = "RGB",
			["zh-CN"] = "",
		},
		["#STCursorSize"] = {
			["en"] = "Cursor size",
			["tr"] = "İmleç boyutu",
			["zh-TW"] = "游標大小",
			["zh-CN"] = "",
			["ru"] = "Размер курсора",
			["ja"] = "カーソルサイズ",
		},
		["#STSkins"] = {
			["en"] = "Skins",
			["tr"] = "Kaplamalar",
			["zh-TW"] = "Skins",
			["zh-CN"] = "",
			["ru"] = "Облики",
			["ja"] = "Skins",
		},
		["#TotalMap"] = {
			["en"] = "Total Map Played",
			["tr"] = "Oynanan Toplam Harita",
			["zh-TW"] = "總遊玩次數",
			["zh-CN"] = "",
			["ru"] = "Всего карт сыграно",
			["ja"] = "総プレイ回数",
		},
		["#DiscServer"] = {
			["en"] = "Disconnected to server!",
			["tr"] = "Sunucu bağlantısı kesildi!",
			["zh-TW"] = "與伺服器斷開連接!",
			["zh-CN"] = "",
			["ru"] = "Отключены от сервера!",
			["ja"] = "サーバーに切断されました！",
		},
		["#STFPoint"] = {
			["en"] = "Followpoints",
			["tr"] = "Takip noktaları",
			["zh-TW"] = "物件跟隨指示",
			["zh-CN"] = "",
			["ru"] = "Следующие точки",
			["ja"] = "フォローポイント",
		},
		["#DLDownloading"] = {
			["en"] = "Downloading beatmap(s)..",
			["tr"] = "Beatmap indiriliyor..",
			["zh-TW"] = "正在下載圖譜",
			["zh-CN"] = "",
			["ru"] = "Скачивание карт(-ы)..",
			["ja"] = "ビートマップをダウンロード中",
		},
		["#STSkin"] = {
			["en"] = "Skin",
			["tr"] = "Kaplama",
			["zh-TW"] = "外觀",
			["zh-CN"] = "",
			["ru"] = "Облик",
			["ja"] = "スキン",
		},
		["#STEVol"] = {
			["en"] = "Effects",
			["tr"] = "Efektler",
			["zh-TW"] = "其他音效",
			["zh-CN"] = "",
			["ru"] = "Эффекты",
			["ja"] = "効果",
		},
		["#STBlur"] = {
			["en"] = "Blur shader",
			["tr"] = "Bulanıklık",
			["zh-TW"] = "畫面模糊",
			["zh-CN"] = "",
			["ru"] = "Шейдер размытия",
			["ja"] = "ブラーシェーダー",
		},
		["#STBeheaves"] = {
			["en"] = "Change the way osu! beheaves",
			["tr"] = "Osu'nun çalışma şeklini değiştir",
			["zh-TW"] = "個人化你的 osu! 設定",
			["zh-CN"] = "",
			["ru"] = "Измените поведение osu!",
			["ja"] = "osu!のパーソナル化",
		},
		["#STNoEdgeSound"] = {
			["en"] = "Disable slider edge sound",
			["tr"] = "Kenar kaydıraç sesini devre dışı bırak",
			["zh-TW"] = "關閉滑條的額外擊中音效",
			["zh-CN"] = "",
			["ru"] = "Отключить звук края ползунка",
			["ja"] = "スライダーのエッジ音を無効にする",
		},
		["#STHVol"] = {
			["en"] = "Hitsound",
			["tr"] = "Tık sesi",
			["zh-TW"] = "擊中音效",
			["zh-CN"] = "",
			["ru"] = "Звук попадания",
			["ja"] = "ヒットサウンド",
		},
		["#STSmoothObj"] = {
			["en"] = "Smoother hitcircles",
			["tr"] = "Daha pürüzsüz tıklama daireleri",
			["zh-TW"] = "物件平滑化",
			["zh-CN"] = "",
			["ru"] = "Гладкие ноты",
			["ja"] = "オブジェクトスムージングになる",
		},
		["#STSnaking"] = {
			["en"] = "Snaking sliders",
			["tr"] = "Kıvrılan kaydıraçlar",
			["zh-TW"] = "滑條漸出",
			["zh-CN"] = "",
			["ru"] = "Движущиеся ползунки",
			["ja"] = "伸びるスライダー",
		},
		["#STPerfectHit"] = {
			["en"] = "Show perfect hits",
			["tr"] = "Mükemmel tıkları göster",
			["zh-TW"] = "顯示完美打擊",
			["zh-CN"] = "",
			["ru"] = "Показывать идеальные попадания",
			["ja"] = "完璧なヒットを見せる",
		},
		["#STHitError"] = {
			["en"] = "Hit-error bar",
			["tr"] = "Tık hata çubuğu",
			["zh-TW"] = "準確度指示器",
			["zh-CN"] = "",
			["ru"] = "Панель ошибки при попадании",
			["ja"] = "精度指標",
		},
		["#STNoOBJFlash"] = {
			["en"] = "Disable flashing on hitobjects",
			["tr"] = "Tık objelerinde yanıp sönmeyi devre dışı bırak",
			["zh-TW"] = "關閉物件閃爍效果",
			["zh-CN"] = "",
			["ru"] = "Отключить мигание на игровых объектах",
			["ja"] = "ヒットオブジェクトの点滅無効にする",
		},
		["#DLNoResult"] = {
			["en"] = "No Result",
			["tr"] = "Sonuç Yok",
			["zh-TW"] = "無結果",
			["zh-CN"] = "",
			["ru"] = "Нет результатов",
			["ja"] = "結果なし",
		},
		["#DLSearch"] = {
			["en"] = "Search",
			["tr"] = "Ara",
			["zh-TW"] = "搜尋",
			["zh-CN"] = "",
			["ru"] = "Поиск",
			["ja"] = "検索",
		},
		["#DLUnpacked"] = {
			["en"] = "Unpacked successfully",
			["tr"] = "Başarıyla çıkarıldı",
			["zh-TW"] = "導入完成",
			["zh-CN"] = "",
			["ru"] = "Распаковка выполнена",
			["ja"] = "導入が完了しました",
		},
		["#STInterfaceSound"] = {
			["en"] = "Interface voices",
			["tr"] = "Arayüz sesleri",
			["zh-TW"] = "介面語音",
			["zh-CN"] = "",
			["ru"] = "Голосовое приветствие",
			["ja"] = "メニューの音声効果を有効化",
		},
		["#STDownloader"] = {
			["en"] = "Downloader",
			["tr"] = "İndirici",
			["zh-TW"] = "圖譜下載器",
			["zh-CN"] = "",
			["ru"] = "Загрузчик",
			["ja"] = "ダウンローダー",
		},
		["#STSmoothBG"] = {
			["en"] = "Smooth background",
			["tr"] = "Pürüzsüz arka plan",
			["zh-TW"] = "背景平滑化",
			["zh-CN"] = "",
			["ru"] = "Плавный фон",
			["ja"] = "スムーズな背景",
		},
		["#BMObjects"] = {
			["en"] = "Objects",
			["tr"] = "Objeler",
			["zh-TW"] = "物件數量",
			["zh-CN"] = "",
			["ru"] = "Объекты",
			["ja"] = "オブジェクト",
		},
		["#STCursorTrailLife"] = {
			["en"] = "Trail lifetime",
			["tr"] = "İz süresi",
			["zh-TW"] = "軌跡長度",
			["zh-CN"] = "",
			["ru"] = "Длительность следа",
			["ja"] = "軌跡の長さ",
		},
		["#STGeneral"] = {
			["en"] = "General",
			["tr"] = "Genel",
			["zh-TW"] = "一般",
			["zh-CN"] = "",
			["ru"] = "Общее",
			["ja"] = "一般",
		},
		["#STBGDim"] = {
			["en"] = "Background dim",
			["tr"] = "Arka plan parlaklığı",
			["zh-TW"] = "背景亮度",
			["zh-CN"] = "",
			["ru"] = "Затемнение фона",
			["ja"] = "メニューの明るさ",
		},
		["#C2S"] = {
			["en"] = "Click to start",
			["tr"] = "Başlamak için tıkla",
			["zh-TW"] = "點擊開始",
			["zh-CN"] = "",
			["ru"] = "Нажмите, чтобы начать",
			["ja"] = "クリックで開始",
		},
		["#STSignIn"] = {
			["en"] = "Sign in",
			["tr"] = "Kayıt ol",
			["zh-TW"] = "登入",
			["zh-CN"] = "",
			["ru"] = "Войти",
			["ja"] = "ログイン",
		},
		["#STGraphics"] = {
			["en"] = "Graphics",
			["tr"] = "Grafik",
			["zh-TW"] = "畫面",
			["zh-CN"] = "",
			["ru"] = "Графика",
			["ja"] = "グラフィック",
		},
		["#STCheckThumbnails"] = {
			["en"] = "Check if map has more than one thumbnails",
			["tr"] = "Haritanın birden fazla küçük resmi olup olmadığını kontrol et",
			["zh-TW"] = "檢查圖譜是否有一張以上的背景",
			["zh-CN"] = "",
			["ru"] = "Проверять, есть ли на карте более одной миниатюры.",
			["ja"] = "ビートマップに複数のサムネイルがあるかチェックする",
		},
		["#STMenuSnow"] = {
			["en"] = "Menu snow",
			["tr"] = "Menü karı",
			["zh-TW"] = "降雪效果",
			["zh-CN"] = "",
			["ru"] = "Снег в меню",
			["ja"] = "メインメニューに雪のビジュアル表示する",
		},
		["#STPrevImg"] = {
			["en"] = "Preview Image",
			["tr"] = "Görseli Önizle",
			["zh-TW"] = "預覽圖片",
			["zh-CN"] = "",
			["ru"] = "Изображение предпросмотра",
			["ja"] = "プレビュー画像",
		},
		["#DLStopSound"] = {
			["en"] = "Stop sounds",
			["tr"] = "Sesleri durdur",
			["zh-TW"] = "停止預覽",
			["zh-CN"] = "",
			["ru"] = "Остановить звуки",
			["ja"] = "音を止める",
		},
		["#STLoadSkinImage"] = {
			["en"] = "Load skin images (WIP, NOT RECOMMENDED)",
			["tr"] = "Kaplama görsellerini yükle (DENEYSELDİR, ÖNERİLMEZ)",
			["zh-TW"] = "載入Skin材質 (未完成，不建議)",
			["zh-CN"] = "",
			["ru"] = "Загрузить изображения облика (В РАЗРАБОТКЕ, НЕ РЕКОМЕНДУЕТСЯ)",
			["ja"] = "スキン素材をロード（未完成、お勧めしません）",
		},
		["#STDisableMouse"] = {
			["en"] = "Disable mouse buttons",
			["tr"] = "Fare tuşlarını devre dışı bırak",
			["zh-TW"] = "停用滑鼠按鍵",
			["zh-CN"] = "",
			["ru"] = "Отключить кнопки мыши",
			["ja"] = "マウスボタンを無効にする",
		},
		["#STSelectSong"] = {
			["en"] = "Song Select",
			["tr"] = "Şarkı Seç",
			["zh-TW"] = "圖譜選取",
			["zh-CN"] = "",
			["ru"] = "Выбор песни",
			["ja"] = "曲選択",
		},
		["#STAvatarFrame"] = {
			["en"] = "Load avatar frames",
			["tr"] = "Avatar çerçevelerini yükle",
			["zh-TW"] = "載入頭像框",
			["zh-CN"] = "",
			["ru"] = "Загрузить рамки аватаров",
			["ja"] = "アバターフレームの読み込み",
		},
		["#STCustomName"] = {
			["en"] = "Name for leaderboard",
			["tr"] = "Skor tablosu için ad",
			["zh-TW"] = "自訂名稱",
			["zh-CN"] = "",
			["ru"] = "Имя для таблицы рекордов",
			["ja"] = "カスタム名",
		},
		["#STGameplay"] = {
			["en"] = "Gameplay",
			["tr"] = "Oynanış",
			["zh-TW"] = "遊玩設定",
			["zh-CN"] = "",
			["ru"] = "Игра",
			["ja"] = "ゲームプレイ",
		},
		["#DLImport"] = {
			["en"] = "Import",
			["tr"] = "İçeri aktar",
			["zh-TW"] = "導入圖譜",
			["zh-CN"] = "",
			["ru"] = "Импорт",
			["ja"] = "インポート",
		},
		["#STNoRender"] = {
			["en"] = "Stop world rendering (Highly recommended)",
			["tr"] = "Dünyayı işlemeyi durdur (Şiddetle tavsiye edilir)",
			["zh-TW"] = "停止世界渲染",
			["zh-CN"] = "",
			["ru"] = "Остановить обработку мира (настоятельно рекомендуется)",
			["ja"] = "ワールドレンダリング停止",
		},
		["#ServerCheck"] = {
			["en"] = "Checking server status...",
			["tr"] = "Sunucu durumu kontrol ediliyor...",
			["zh-TW"] = "嘗試連接至伺服器...",
			["zh-CN"] = "",
			["ru"] = "Проверка состояния сервера...",
			["ja"] = "サーバーの状態をチェックしています...",
		},
		["#BMSpinners"] = {
			["en"] = "Spinners",
			["tr"] = "Topaç",
			["zh-TW"] = "轉盤",
			["zh-CN"] = "",
			["ru"] = "Спиннеры",
			["ja"] = "スビナー",
		},
		["#DLType2S"] = {
			["en"] = "Type to search!",
			["tr"] = "Aramak için yazın!",
			["zh-TW"] = "搜尋圖譜!",
			["zh-CN"] = "",
			["ru"] = "Начните печатать!",
			["ja"] = "検索ビートマップ!",
		},
		["#STMouse"] = {
			["en"] = "Mouse",
			["tr"] = "Fare",
			["zh-TW"] = "滑鼠",
			["zh-CN"] = "",
			["ru"] = "Мышь",
			["ja"] = "マウス",
		},
		["#STLanguage"] = {
			["en"] = "Language",
			["tr"] = "Dil",
			["zh-TW"] = "語言",
			["zh-CN"] = "",
			["ru"] = "Язык",
			["ja"] = "言語",
		},
		["#STKeyboard"] = {
			["en"] = "Keyboard",
			["tr"] = "Klavye",
			["zh-TW"] = "鍵盤",
			["zh-CN"] = "",
			["ru"] = "Клавиатура",
			["ja"] = "キーボード",
		},
		["#STLoggedIn-No"] = {
			["en"] = "Not logged in",
			["tr"] = "Giriş yapılmamış",
			["zh-TW"] = "未登入",
			["zh-CN"] = "",
			["ru"] = "Не вошли",
			["ja"] = "ログインしていません",
		},
		["#RKS"] = {
			["en"] = "Ranking Score",
			["tr"] = "Sıralama Skoru",
			["zh-TW"] = "積分",
			["zh-CN"] = "",
			["ru"] = "Рейтинг по очкам",
			["ja"] = "ランキングスコア",
		},
		["#STWelcome"] = {
			["en"] = "Welcome : ",
			["tr"] = "Hoşgeldiniz : ",
			["zh-TW"] = "歡迎 : ",
			["zh-CN"] = "",
			["ru"] = "Добро пожаловать : ",
			["ja"] = "ようこそ : ",
		},
		["#STDisplayLanguage"] = {
			["en"] = "Language",
			["tr"] = "Dil",
			["zh-TW"] = "語言",
			["zh-CN"] = "",
			["ru"] = "Язык",
			["ja"] = "言語",
		},
		["#STSounds"] = {
			["en"] = "Sounds",
			["tr"] = "Ses",
			["zh-TW"] = "音效",
			["zh-CN"] = "",
			["ru"] = "Звуки",
			["ja"] = "音響効果",
		},
		["#ConnServer"] = {
			["en"] = "Connected to server!",
			["tr"] = "Sunucuya bağlanıldı!",
			["zh-TW"] = "已連線到伺服器!",
			["zh-CN"] = "",
			["ru"] = "Подключены к серверу!",
			["ja"] = "サーバーに接続しました！",
		},
		["#DLPlaceholder"] = {
			["en"] = "Search beatmap name / mapper",
			["tr"] = "Beatmap adı / yapımcısı",
			["zh-TW"] = "搜尋圖譜 / 製譜者",
			["zh-CN"] = "",
			["ru"] = "Поиск по имени карты / картодела",
			["ja"] = "検索ビートマップの名前 / 譜面制作者",
		},
		["#STWriteCache"] = {
			["en"] = "Write beatmap cache (Faster load time)",
			["tr"] = "Beatmap verisini kaydet (Daha hızlı açılma)",
			["zh-TW"] = "寫入圖譜快取",
			["zh-CN"] = "",
			["ru"] = "Запись кэша карт (Ускоренное время загрузки)",
			["ja"] = "ビートマップキャッシュの書き込み",
		},
		["#STOptions"] = {
			["en"] = "Options",
			["tr"] = "Ayarlar",
			["zh-TW"] = "設定",
			["zh-CN"] = "",
			["ru"] = "Настройки",
			["ja"] = "設定",
		},
		["#RankingNum"] = {
			["en"] = "Ranking",
			["tr"] = "Sıralama",
			["zh-TW"] = "排名",
			["zh-CN"] = "",
			["ru"] = "Рейтинг",
			["ja"] = "ランキング",
		},
		["#BMCircles"] = {
			["en"] = "Circles",
			["tr"] = "Daireler",
			["zh-TW"] = "圓圈",
			["zh-CN"] = "",
			["ru"] = "Кружки",
			["ja"] = "サークル",
		},
		["#STPerformance"] = {
			["en"] = "Performance",
			["tr"] = "Performans",
			["zh-TW"] = "性能",
			["zh-CN"] = "",
			["ru"] = "Производительность",
			["ja"] = "パフォーマンス",
		},
		["#STIdentify"] = {
			["en"] = "Identify",
			["tr"] = "Kimlik doğrula",
			["zh-TW"] = "身分驗證",
			["zh-CN"] = "",
			["ru"] = "Определить",
			["ja"] = "身分確認",
		},
		["#DLCurPage"] = {
			["en"] = "Current page",
			["tr"] = "Geçerli sayfa",
			["zh-TW"] = "目前頁面",
			["zh-CN"] = "",
			["ru"] = "Текущая страница",
			["ja"] = "現在のページ",
		},
		["#STStatus"] = {
			["en"] = "Status",
			["tr"] = "Durum",
			["zh-TW"] = "狀態",
			["zh-CN"] = "",
			["ru"] = "Состояние",
			["ja"] = "状態",
		},
		["#STNoOutline"] = {
			["en"] = "Don't draw slider's outlines",
			["tr"] = "Kaydıraçların dış çizgisini çizme",
			["zh-TW"] = "不渲染滑條外圍線條",
			["zh-CN"] = "",
			["ru"] = "Не показывать контуры ползунков",
			["ja"] = "スライダーのアウトラインを描かない",
		},
		["#STLeaderboard"] = {
			["en"] = "Leaderboard",
			["tr"] = "Skor Tablosu",
			["zh-TW"] = "排行榜",
			["zh-CN"] = "",
			["ru"] = "Таблица рекордов",
			["ja"] = "リーダーボード",
		},
		["#STTestSlider"] = {
			["en"] = "Use experimental sliders",
			["tr"] = "Deneysel kaydıraçları kullan",
			["zh-TW"] = "使用測試版滑條",
			["zh-CN"] = "",
			["ru"] = "Использовать экспериментальные ползунки",
			["ja"] = "ベータスライダーを使用",
		},
}

OSU.Trans = "en"

function OSU:LookupTranslate(index)
	if(OSU.Lang[index] == nil) then return "Undefined" end
	local ret = OSU.Lang[index][OSU.Trans]
	if(ret == nil) then
		return OSU.Lang[index]["en"]
	end
	return ret
end
